default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: dic_sample_development

test:
  <<: *default
  database: dic_sample_test

production:
  <<: *default
  database: dic_sample_production
  username: dic_sample
  password: <%= ENV['DIC_SAMPLE_DATABASE_PASSWORD'] %>
